$ErrorActionPreference = 'Stop'
$baseUrl = 'https://italianoconmartin.com'
$ctaUrl = 'https://preply.com/it/tutor/5086125'
$langs = @('en','es','fr','cs','pl','tr','de','ja')
$copy = @{
  en=@{name='English'; title='Learn Italian online with Martin'; desc='Private online Italian lessons with Martin, clear grammar, real conversation and free A1-C1 learning materials.'; nav1='Readings'; nav2='Grammar'; nav3='Stories'; kicker='Private online lessons - A1-C1'; h1='Speak Italian with more confidence, one lesson at a time.'; lead='Practical lessons built around your level, interests and goals. Study with a native teacher and turn grammar, stories and new words into real conversation.'; free='Free materials'; cta='Book on Preply'; readTitle='Graded Italian readings'; readDesc='Free Italian readings about science, culture, technology and everyday life, organized for learners from A1 to C1.'; grammarTitle='Italian grammar from A1 to C1'; grammarDesc='Clear grammar explanations and interactive exercises for every level.'; storyTitle='Complete Italian stories from A1 to C1'; storyDesc='Classic stories rewritten in graded Italian, with vocabulary and questions for conversation practice.'}
  es=@{name='Español'; title='Aprende italiano online con Martin'; desc='Clases individuales de italiano online con Martin, gramatica clara, conversacion real y materiales gratuitos A1-C1.'; nav1='Lecturas'; nav2='Gramatica'; nav3='Historias'; kicker='Clases individuales online - A1-C1'; h1='Habla italiano con mas seguridad, una clase a la vez.'; lead='Clases practicas y personalizadas segun tu nivel, tus intereses y tus objetivos. Estudia con un profesor nativo y convierte la gramatica y las lecturas en conversacion real.'; free='Materiales gratuitos'; cta='Reservar en Preply'; readTitle='Lecturas graduadas en italiano'; readDesc='Lecturas gratuitas en italiano sobre ciencia, cultura, tecnologia y vida cotidiana, de A1 a C1.'; grammarTitle='Gramatica italiana de A1 a C1'; grammarDesc='Explicaciones claras y ejercicios interactivos para todos los niveles.'; storyTitle='Historias completas en italiano de A1 a C1'; storyDesc='Historias clasicas adaptadas por nivel, con vocabulario y preguntas para practicar.'}
  fr=@{name='Francais'; title='Apprendre l italien en ligne avec Martin'; desc='Cours particuliers d italien en ligne avec Martin, grammaire claire, conversation reelle et ressources gratuites A1-C1.'; nav1='Lectures'; nav2='Grammaire'; nav3='Histoires'; kicker='Cours particuliers en ligne - A1-C1'; h1='Parle italien avec plus de confiance, un cours apres l autre.'; lead='Des cours pratiques et personnalises selon ton niveau, tes interets et tes objectifs. Etudie avec un professeur natif et transforme la grammaire et les lectures en conversation.'; free='Ressources gratuites'; cta='Reserver sur Preply'; readTitle='Lectures graduees en italien'; readDesc='Lectures gratuites en italien sur la science, la culture, la technologie et la vie quotidienne, de A1 a C1.'; grammarTitle='Grammaire italienne de A1 a C1'; grammarDesc='Explications claires et exercices interactifs pour tous les niveaux.'; storyTitle='Histoires completes en italien de A1 a C1'; storyDesc='Histoires classiques adaptees a chaque niveau, avec vocabulaire et questions.'}
  cs=@{name='Cestina'; title='Ucte se italsky online s Martinem'; desc='Individualni online lekce italstiny s Martinem, jasna gramatika, skutecna konverzace a materialy zdarma A1-C1.'; nav1='Cetba'; nav2='Gramatika'; nav3='Pribehy'; kicker='Individualni online lekce - A1-C1'; h1='Mluvte italsky jisteji, lekci za lekci.'; lead='Prakticke lekce prizpusobene vasi urovni, zajmum a cilum. Ucte se s rodilym ucitelem a promen te gramatiku a cetbu ve skutecnou konverzaci.'; free='Materialy zdarma'; cta='Rezervovat na Preply'; readTitle='Italska cetba podle urovne'; readDesc='Clanky zdarma v italstine o vede, kulture, technologiich a kazdodennim zivote od A1 do C1.'; grammarTitle='Italska gramatika od A1 do C1'; grammarDesc='Jasna vysvetleni a interaktivni cviceni pro vsechny urovne.'; storyTitle='Uplne italske pribehy od A1 do C1'; storyDesc='Klasicke pribehy prevypravene podle urovne, se slovni zasobou a otazkami.'}
  pl=@{name='Polski'; title='Ucz sie wloskiego online z Martinem'; desc='Indywidualne lekcje wloskiego online z Martinem, jasna gramatyka, prawdziwa rozmowa i bezplatne materialy A1-C1.'; nav1='Czytanki'; nav2='Gramatyka'; nav3='Opowiadania'; kicker='Indywidualne lekcje online - A1-C1'; h1='Mow po wlosku pewniej, lekcja po lekcji.'; lead='Praktyczne lekcje dopasowane do Twojego poziomu, zainteresowan i celow. Ucz sie z native speakerem i zamieniaj gramatyke oraz teksty w prawdziwa rozmowe.'; free='Bezplatne materialy'; cta='Zarezerwuj na Preply'; readTitle='Wloskie czytanki wedlug poziomu'; readDesc='Bezplatne teksty po wlosku o nauce, kulturze, technologii i codziennym zyciu od A1 do C1.'; grammarTitle='Gramatyka wloska od A1 do C1'; grammarDesc='Jasne wyjasnienia i interaktywne cwiczenia dla kazdego poziomu.'; storyTitle='Pelne opowiadania po wlosku od A1 do C1'; storyDesc='Klasyczne opowiadania dostosowane do poziomu, ze slownictwem i pytaniami.'}
  tr=@{name='Turkce'; title='Martin ile cevrim ici Italyanca ogrenin'; desc='Martin ile birebir cevrim ici Italyanca dersleri, anlasilir dilbilgisi, gercek konusma ve ucretsiz A1-C1 materyaller.'; nav1='Okumalar'; nav2='Dilbilgisi'; nav3='Hikayeler'; kicker='Birebir cevrim ici dersler - A1-C1'; h1='Her derste Italyancayi daha guvenle konusun.'; lead='Seviyenize, ilgi alanlariniza ve hedeflerinize gore hazirlanan pratik dersler. Ana dili Italyanca olan bir ogretmenle calisin ve dilbilgisini gercek konusmaya donusturun.'; free='Ucretsiz materyaller'; cta='Preply de rezervasyon yap'; readTitle='Seviyeye uygun Italyanca okumalar'; readDesc='A1-C1 seviyeleri icin bilim, kultur, teknoloji ve gunluk yasam hakkinda ucretsiz metinler.'; grammarTitle='A1 den C1 e Italyanca dilbilgisi'; grammarDesc='Her seviyeye uygun anlasilir aciklamalar ve etkilesimli alistirmalar.'; storyTitle='A1 den C1 e tam Italyanca hikayeler'; storyDesc='Kelime listeleri ve konusma sorulari iceren klasik hikayeler.'}
  de=@{name='Deutsch'; title='Italienisch online mit Martin lernen'; desc='Individueller Italienischunterricht online mit Martin, klare Grammatik, echte Gespraeche und kostenlose Lernmaterialien von A1 bis C1.'; nav1='Lesetexte'; nav2='Grammatik'; nav3='Geschichten'; kicker='Individueller Online-Unterricht - A1-C1'; h1='Sprich Italienisch mit mehr Sicherheit, Stunde fuer Stunde.'; lead='Praktischer Unterricht passend zu deinem Niveau, deinen Interessen und deinen Zielen. Lerne mit einem Muttersprachler und bringe Grammatik und Texte ins echte Gespraech.'; free='Kostenlose Materialien'; cta='Auf Preply buchen'; readTitle='Italienische Lesetexte nach Niveau'; readDesc='Kostenlose italienische Texte ueber Wissenschaft, Kultur, Technologie und Alltag fuer A1 bis C1.'; grammarTitle='Italienische Grammatik von A1 bis C1'; grammarDesc='Klare Erklaerungen und interaktive Uebungen fuer jedes Niveau.'; storyTitle='Vollstaendige italienische Geschichten von A1 bis C1'; storyDesc='Klassische Geschichten nach Niveau angepasst, mit Wortschatz und Fragen.'}
  ja=@{name='Japanese'; title='Learn Italian online with Martin'; desc='Private online Italian lessons with Martin, clear grammar, real conversation and free A1-C1 learning materials.'; nav1='Readings'; nav2='Grammar'; nav3='Stories'; kicker='Online lessons - A1-C1'; h1='Speak Italian with more confidence, one lesson at a time.'; lead='Practical Italian lessons built around your level, interests and goals. Study with a native teacher and turn grammar, stories and new words into real conversation.'; free='Free materials'; cta='Book on Preply'; readTitle='Graded Italian readings'; readDesc='Free Italian readings about science, culture, technology and everyday life, organized for learners from A1 to C1.'; grammarTitle='Italian grammar from A1 to C1'; grammarDesc='Clear grammar explanations and interactive exercises for every level.'; storyTitle='Complete Italian stories from A1 to C1'; storyDesc='Classic stories rewritten in graded Italian, with vocabulary and questions for conversation practice.'}
}

function Esc($value) { return [System.Net.WebUtility]::HtmlEncode([string]$value) }
function Alt($lang, $kind) {
  $itPath = @{home='/'; readings='/letture/'; grammar='/grammatica/'; stories='/favole/'}[$kind]
  $slug = @{home=''; readings='readings'; grammar='grammar'; stories='stories'}[$kind]
  $out = @('<link rel="alternate" hreflang="it" href="{0}{1}">' -f $baseUrl,$itPath)
  foreach ($l in $langs) { $target = if ($slug) { "$baseUrl/$l/$slug/" } else { "$baseUrl/$l/" }; $out += '<link rel="alternate" hreflang="{0}" href="{1}">' -f $l,$target }
  $out += '<link rel="alternate" hreflang="x-default" href="{0}{1}">' -f $baseUrl,$itPath
  $out -join "`n  "
}
function MakePage($lang, $kind) {
  $d=$copy[$lang]; $slug=@{home=''; readings='readings'; grammar='grammar'; stories='stories'}[$kind]
  $folder=if($kind -eq 'home'){$lang}else{"$lang/$slug"}; $root=if($kind -eq 'home'){'../'}else{'../../'}; $localHome="$root$lang/"; $path="/$folder/"
  $title=if($kind -eq 'home'){$d.title}else{ @{readings=$d.readTitle;grammar=$d.grammarTitle;stories=$d.storyTitle}[$kind] }
  $desc=if($kind -eq 'home'){$d.desc}else{ @{readings=$d.readDesc;grammar=$d.grammarDesc;stories=$d.storyDesc}[$kind] }
  $lead=if($kind -eq 'home'){$d.lead}else{$desc}
  $cards = if($kind -eq 'home') { @(@{t=$d.grammarTitle;x=$d.grammarDesc;h='grammar/'},@{t=$d.storyTitle;x=$d.storyDesc;h='stories/'},@{t=$d.readTitle;x=$d.readDesc;h='readings/'}) } else { @(@{t=$title;x=$lead;h=@{readings='/letture/';grammar='/grammatica/';stories='/favole/'}[$kind]}) }
  $cardHtml=($cards|%{ '<a class="home-card" href="{0}"><span class="badge">A1-C1</span><h2>{1}</h2><p>{2}</p><strong>{3} <span aria-hidden="true">&rarr;</span></strong></a>' -f $_.h,(Esc $_.t),(Esc $_.x),(Esc $(if($kind -eq 'home'){'Explore'}else{'Open'})) }) -join "`n"
  $main=if($kind -eq 'home'){ '<section class="landing-hero"><div class="container landing-grid"><div class="hero-copy"><p class="hero-kicker">'+(Esc $d.kicker)+'</p><p class="eyebrow">Italiano con Martin</p><h1>'+ (Esc $d.h1) +'</h1><p class="lead">'+(Esc $d.lead)+'</p><div class="actions"><a class="button primary hero-cta" href="'+$ctaUrl+'" target="_blank" rel="noopener">'+(Esc $d.cta)+'</a></div></div><div class="teacher-photo-wrap"><div class="teacher-photo-frame"><img class="teacher-photo" src="'+$root+'assets/martin-portrait.webp" alt="Martin, insegnante di italiano per stranieri" width="800" height="1067"></div></div></div></section><section class="section start-section"><div class="container section-heading"><div><p class="eyebrow">'+(Esc $d.free)+'</p><h2>'+ (Esc $d.title) +'</h2></div><p>Explore the resources and bring your questions to class.</p></div><div class="container home-grid">'+$cardHtml+'</div></section>' } else { '<section class="page-intro"><div class="container"><p class="eyebrow">'+(Esc $d.free)+'</p><h1>'+ (Esc $title) +'</h1><p class="lead">'+(Esc $lead)+'</p></div></section><section class="section compact-top"><div class="container home-grid">'+$cardHtml+'</div></section>' }
  $html='<!doctype html><html lang="'+$lang+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+(Esc $title)+' | Italiano con Martin</title><meta name="description" content="'+(Esc $desc)+'"><link rel="canonical" href="'+$baseUrl+$path+'"><meta name="robots" content="index,follow,max-image-preview:large">'+(Alt $lang $kind)+'<meta property="og:type" content="website"><meta property="og:title" content="'+(Esc $title)+'"><meta property="og:description" content="'+(Esc $desc)+'"><meta property="og:url" content="'+$baseUrl+$path+'"><meta property="og:image" content="'+$baseUrl+'/assets/martin-portrait.webp"><link rel="stylesheet" href="'+$root+'styles.css"><link rel="icon" href="'+$root+'favicon.png" type="image/png"></head><body><header class="site-header"><div class="container nav-wrap"><a class="brand" href="'+$localHome+'"><img class="brand-avatar" src="'+$root+'assets/martin-photo.svg" alt="Martin"><span>Italiano con Martin</span></a><nav><a href="'+$localHome+'readings/">'+(Esc $d.nav1)+'</a><a href="'+$localHome+'grammar/">'+(Esc $d.nav2)+'</a><a href="'+$ctaUrl+'" class="nav-cta" target="_blank" rel="noopener">'+(Esc $d.cta)+'</a></nav></div></header><main>'+$main+'<section class="conversion-section"><div class="container conversion-card"><div><h2>'+ (Esc $d.cta) +'</h2><p>'+ (Esc $d.lead) +'</p></div><a class="button light" href="'+$ctaUrl+'" target="_blank" rel="noopener">'+(Esc $d.cta)+'</a></div></section></main><footer><div class="container footer-grid"><div><strong>Italiano con Martin</strong><p>'+ (Esc $d.desc) +'</p></div><div><a href="'+$localHome+'readings/">'+(Esc $d.nav1)+'</a><a href="'+$localHome+'grammar/">'+(Esc $d.nav2)+'</a><a href="'+$ctaUrl+'" target="_blank" rel="noopener">Preply</a></div></div></footer><script src="'+$root+'script.js"></script></body></html>'
  $dest=Join-Path $PSScriptRoot "..\$folder\index.html"; New-Item -ItemType Directory -Force (Split-Path $dest)|Out-Null; Set-Content -LiteralPath $dest -Value $html -Encoding UTF8
}
foreach($l in $langs){MakePage $l 'home'; foreach($k in @('readings','grammar','stories')){MakePage $l $k}}
